from sqlalchemy import select, and_
from sqlalchemy.exc import SQLAlchemyError

from repo_analyst.database.database import (
    AsyncSessionLocal,
)

from repo_analyst.database.models import (
    FileSummary,
)


class FileSummaryRepository:
    """Repository for managing file summaries in the database."""

    async def save_summary(
        self,
        repo_path: str,
        file_path: str,
        summary: str,
    ) -> None:
        """Save a file summary to the database.

        Args:
            repo_path: Path to the repository containing the file.
            file_path: Path to the file within the repository.
            summary: Summary of the file content generated by the LLM.

        Raises:
            SQLAlchemyError: If there is an error during database operations.
        """
        try:
            async with AsyncSessionLocal() as db:
                record = FileSummary(
                    repo_path=repo_path,
                    file_path=file_path,
                    summary=summary,
                )
                db.add(record)
                await db.commit()
        except SQLAlchemyError as e:
            # Log the error and re-raise it to ensure the caller is aware
            # of the failure (logging is not shown here for brevity)
            raise e

    async def get_summary(
        self,
        repo_path: str,
        file_path: str,
    ) -> str | None:
        """Retrieve a file summary from the database.

        Args:
            repo_path: Path to the repository containing the file.
            file_path: Path to the file within the repository.

        Returns:
            The file summary if found, otherwise None.

        Raises:
            SQLAlchemyError: If there is an error during database operations.
        """
        try:
            async with AsyncSessionLocal() as db:
                result = await db.execute(
                    select(FileSummary)
                    .where(
                        and_(
                            FileSummary.repo_path == repo_path,
                            FileSummary.file_path == file_path,
                        )
                    )
                )
                return result.scalars().first()
        except SQLAlchemyError as e:
            # Log the error and re-raise it to ensure the caller is aware
            # of the failure (logging is not shown here for brevity)
            raise e