from sqlalchemy import (
    Column,
    Integer,
    Text,
    TIMESTAMP,
    ForeignKey,
    UniqueConstraint,
)
from sqlalchemy.sql import func

from repo_analyst.database.database import Base


class AgentRun(Base):
    """Represents a run of an agent with a specific question and repository context."""

    __tablename__ = "agent_runs"

    id = Column(Integer, primary_key=True, doc="Unique identifier for the agent run")
    question = Column(
        Text, nullable=False, doc="The question or task the agent was asked to address"
    )
    repo_path = Column(
        Text, nullable=False, doc="Path to the repository being analyzed"
    )
    created_at = Column(
        TIMESTAMP,
        server_default=func.now(),
        doc="Timestamp when the agent run was created",
    )

    def __repr__(self):
        return f"<AgentRun(id={self.id}, question='{self.question}', repo_path='{self.repo_path}')>"


class AgentFinding(Base):
    """Stores findings generated by an agent during a specific run."""

    __tablename__ = "agent_findings"

    id = Column(Integer, primary_key=True, doc="Unique identifier for the finding")
    run_id = Column(
        Integer,
        ForeignKey("agent_runs.id"),
        nullable=False,
        doc="Reference to the agent run that generated this finding",
    )
    file_path = Column(
        Text, nullable=False, doc="Path to the file where the finding was detected"
    )
    finding = Column(
        Text, nullable=False, doc="The actual finding or issue identified"
    )
    created_at = Column(
        TIMESTAMP,
        server_default=func.now(),
        doc="Timestamp when the finding was recorded",
    )

    def __repr__(self):
        return f"<AgentFinding(id={self.id}, run_id={self.run_id}, file_path='{self.file_path}')>"


class FileSummary(Base):
    """Stores summaries of files generated by the LLM for repository analysis."""

    __tablename__ = "file_summaries"

    id = Column(Integer, primary_key=True, doc="Unique identifier for the file summary")
    repo_path = Column(
        Text,
        nullable=False,
        doc="Path to the repository containing the file",
    )
    file_path = Column(
        Text,
        nullable=False,
        doc="Path to the file being summarized",
    )
    summary = Column(
        Text,
        nullable=False,
        doc="Summary of the file's content generated by the LLM",
    )
    created_at = Column(
        TIMESTAMP,
        server_default=func.now(),
        doc="Timestamp when the summary was created",
    )

    __table_args__ = (
        UniqueConstraint("repo_path", "file_path", name="uq_repo_file_path"),
    )

    def __repr__(self):
        return f"<FileSummary(id={self.id}, repo_path='{self.repo_path}', file_path='{self.file_path}')>"