from ai_provider import AI
from repo_analyst.logging.spinner import Spinner


class AnswerGenerator:
    """Generates answers to repository analysis questions using AI findings."""

    def __init__(self, ai: AI) -> None:
        """Initialize AnswerGenerator with an AI instance.

        Args:
            ai: AI instance capable of generating text responses.
        """
        self.ai = ai

    async def generate(
        self,
        question: str,
        findings: list[str],
    ) -> str:
        """Generate a repository analysis answer based on findings.

        Args:
            question: The question to answer.
            findings: List of repository findings to use as context.

        Returns:
            Answer generated by the AI based on the findings.

        Raises:
            Exception: If AI generation fails or spinner management fails.
        """
        # Prepare findings text
        findings_text = "\n\n".join(findings)

        # Construct prompt
        prompt = f"""
You are analysing a software repository.

Question:
{question}

Repository Findings:
{findings_text}

Instructions:

- Answer ONLY using the repository findings.
- Do NOT provide generic software engineering explanations.
- Do NOT explain concepts unless they are mentioned in the findings.
- Focus on how this repository implements the concept.
- If the findings do not contain enough information, explicitly say so.
- Reference filenames when relevant.
- Be specific and concrete.

Answer:
"""

        spinner = Spinner("🧠 Local LLM Finalising answer...")
        spinner.start()

        try:
            answer = await self.ai.generate(prompt)
        except Exception as e:
            spinner.stop()
            raise e
        finally:
            spinner.stop()

        return answer