from dataclasses import dataclass, field


@dataclass
class AgentState:
    """Represents the state of an agent during repository analysis.

    This class tracks the agent's progress, findings, and other relevant information
    as it analyzes a repository. It includes fields for tracking the current question,
    repository path, files processed, observations, findings, and the final answer.
    """

    question: str
    """The question or task the agent is currently addressing."""

    repo_path: str
    """Path to the repository being analyzed."""

    files_seen: set[str] = field(default_factory=set)
    """Set of files that the agent has encountered in the repository during traversal."""

    search_results: set[str] = field(default_factory=set)
    """Set of files or content that the agent has found via search operations."""

    files_read: set[str] = field(default_factory=set)
    """Set of files that the agent has read or processed in detail."""

    observations: list[str] = field(default_factory=list)
    """List of observations or notes made by the agent during analysis."""

    findings: list[str] = field(default_factory=list)
    """List of findings or insights made by the agent during analysis."""

    search_completed: bool = False
    """Flag indicating whether the search phase has been completed."""

    summary_search_completed: bool = False
    """Flag indicating whether the summary search phase has been completed."""

    relevant_summaries: list = field(default_factory=list)
    """List of tuples containing (score, summary) for relevant summaries found during analysis."""

    run_id: int | None = None
    """Unique identifier for the current run of the agent."""

    final_answer: str | None = None
    """The final answer generated by the agent, if available."""

    def summary(self):
        """Returns a summary of the agent's state with counts of key elements.

        This is useful for logging progress or monitoring the agent's status during analysis.
        """
        return {
            "run_id": self.run_id,
            "question": self.question,
            "repo_path": self.repo_path,
            "files_seen": len(self.files_seen),
            "files_read": len(self.files_read),
            "search_results": len(self.search_results),
            "observations": len(self.observations),
            "findings": len(self.findings),
            "search_completed": self.search_completed,
        }

    def findings_from_summaries(self):
        """Generate formatted findings from relevant summaries.

        Returns a list of strings in the format "[file_path]\nsummary_content".
        """
        return [
            f"[{summary.file_path}]\n{summary.summary}"
            for score, summary in self.relevant_summaries
        ]

    def __repr__(self):
        """Return a string representation of the AgentState instance."""
        return (
            f"AgentState(run_id={self.run_id}, question='{self.question}', repo_path='{self.repo_path}', "
            f"files_seen={len(self.files_seen)}, files_read={len(self.files_read)}, "
            f"search_results={len(self.search_results)}, observations={len(self.observations)}, "
            f"findings={len(self.findings)}, search_completed={self.search_completed}, "
            f"final_answer={self.final_answer})"
        )